### ISSUE TITLE
utils/antd.css 文件覆盖了引用项目的基础样式

### ISSUE THREAD

**Issue by dadazhouRenee** [Fea-Sin/cr-tax#1]
你好 我想请问下关于assets中引入了 antd.css 
```js
@import (inline) '../src/utils/antd.css';
```
请问这样会导致我项目中原来的antd的样式会被cr-tax的antd.css 样式给覆盖掉
请问这样写的目的是啥呢(麻烦大佬解答下，谢谢^^)

**Comment by Fea-Sin** [comment]
项目中使用 antd 组件
版本是 antd v3.23.2

项目已不再维护，
如果你需要使用本项目我可以加你发布npm包权限
你可以自行升级 antd 并使用

**Comment by dadazhouRenee** [comment]
没关系 我可以自己重新发个包 我就是不太理解里面的写法 想问下的

**Comment by Fea-Sin** [comment]
就是正常使用antd组件库，并引入了它的css
这样写就根antd组件库版本强绑定了，
如果项目中使用了不同的版本确实会有问题

如下写法会更好
@import '~antd/dist/antd.css';

**Comment by dadazhouRenee** [comment]
好呢 我是使用过程中项目中配置了主题色 然后发现引用了 `import 'cr-tax/assets/index.css';` 会覆盖主题色 我再试下你说的写法
还有一个问题想请教下，就是examples里面的效果是可以看的吗
我貌似启动了 不能看到效果 会报`Uncaught SyntaxError: Cannot use import statement outside a module` 这个错，但是发包然后到项目里面看实际效果没有问题 不知道您当时有这个问题吗

**Comment by dadazhouRenee** [comment]
好呢 我是使用过程中项目中配置了主题色 然后发现引用了 import 'cr-tax/assets/index.css'; 会覆盖主题色 我再试下你说的写法

**Comment by Fea-Sin** [comment]
如果是你项目 antd 使用了自定义的主题色
可以直接将 @import  '../src/utils/antd.css'; 去掉，不会影响包的运行

实际上，只要项目中使用 antd，打包完全可以不用引用 antd.css

但是，如果要运行包实例的时候需要引入

**Comment by Fea-Sin** [comment]
还有一个方案不知是否可行，
先引入 import 'cr-tax/assets/index.css'; 
后引入项目 antd 样式 import 'antd/dist/antd.css';

这样 antd 会重载之前样式，这种方案并不好，也可能会有其它问题

**Comment by dadazhouRenee** [comment]
嗯嗯 我两个都试了下 第二种方法的话还是会覆盖一些样式 最后采用了第一种方法 谢谢大佬^^
